language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
env:
  matrix:
   - DJANGO=Django==1.5
   - DJANGO=Django==1.6
   - DJANGO=Django==1.7
   - DJANGO=Django==1.8
install:
 - pip install $DJANGO
 - pip install -r requirements.txt
branches:
 only:
  - devel
script: python manage.py test
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=Django==1.7

